### ISSUE TITLE
cannot recognize emojis with more than one codepoint

### ISSUE THREAD

**Issue by endel** [IonicaBizau/emoji-unicode#11]
Hey there, thanks for your library. I've tried it out but unfortunately it only works for emojis with a single codepoint. 

Take the flag of the united states as an example:

```
$ node
> const emojiUnicode = require("emoji-unicode")
undefined
> emojiUnicode("🇺🇸")
'1f1fa'
```

The result should be:
- 🇺 U+1F1FA
- 🇸 U+1F1F8

More: https://emojipedia.org/flag-for-united-states/

**Comment by sweves** [comment]
fix: https://github.com/IonicaBizau/emoji-unicode/pull/13
